apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y6dm7vk3s-go
  janus-idp.io/tekton: y6dm7vk3s-go
  backstage.io/kubernetes-id: y6dm7vk3s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y6dm7vk3s-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
